name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.6.5", "8.8.4", "8.10.4", "9.0.1"]
        os:  ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - name: Install GHC
        uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.4.0.0
      - name: Show GHC version
        run: |
          ghc --version
          cabal --version
      - name: Select build directory
        run: |
          if [ "$OS" == Windows_NT ]; then
            CABAL_BUILDDIR="D:\\a\\_temp\\dist"
          else
            CABAL_BUILDDIR="dist-newstyle"
          fi

          echo "CABAL_BUILDDIR=$CABAL_BUILDDIR"
          echo "CABAL_BUILDDIR=$CABAL_BUILDDIR" >> $GITHUB_ENV

      - name: Set cache version
        run: echo "CACHE_VERSION=9w76Z3Q" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - name: Update Hackage index
        run: cabal update

      - name: Cache cabal store
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-store-${{ env.CACHE_VERSION }}-${{ matrix.ghc }}-${{ matrix.os }}

      - name: Use cabal.project.ci
        run: cp cabal.project.ci cabal.project.local

      - name: Build dependencies
        run: cabal --builddir="$CABAL_BUILDDIR" build --only-dependencies -fall all

      - name: Build tasty-package
        run: cabal --builddir="$CABAL_BUILDDIR" build -fall all
